### ISSUE TITLE
API functions needed to get/set user profile info

### ISSUE THREAD

**Issue by vllry** [vllry/seng299#16]
Need to be able to get all user info.

Need to be able to set:
- Student ID
- Department
- First name
- Last name

**Comment by BoyangJ** [comment]
getting profile info does not return user type and department.

Are you sure user registration stores department? The users in the database currently have no "department" quality.

**Comment by BoyangJ** [comment]
getting profile info does not return password.

**Comment by vllry** [comment]
The API call returns all data about the user, but some users never had type/department set. I'll modify the backend to provide defaults and delete the old users.

Why do you need access the user's password? (The schema suppresses it by default since we have no reason to query it and having it visible is a moderate security risk)

**Comment by vllry** [comment]
I've given studentid, usertype, and department default values, so they'll always exist in the results.

I also deleted the current users from the database.

**Comment by BoyangJ** [comment]
The profile page will include password (displayed as '_'s) so the user can choose to change their password. I think it should at least reflect the length of your password correctly in '_'s
