### ISSUE TITLE
Registering a faculty user crashes server.

### ISSUE THREAD

**Issue by BoyangJ** [vllry/seng299#18]
creating a new user (either through website or postman) with department as "faculty" causes the server to crash. server.js needs to be rerun from command line to restart.

**Comment by vllry** [comment]
There was a problem with residual constraints in mongodb, the issue is fixed.

**Comment by vllry** [comment]
We've actually run into that sort of problem a few times - indices need to manually be deleted from mongodb, removing them from our code isn't enough. Oops!
